const gifs = {
    MiniGifAviso:                    'https://media.tenor.com/images/70584b7a6c3869052d61ae59dcbf9632/tenor.gif',
    MiniGifSalaErrada:               'https://c.tenor.com/8XDC43z6VygAAAAi/robot-angry.gif',
    MiniGifErro:                     'https://media.tenor.com/images/9b6676bde88262d50a7b2b2620bf8768/tenor.gif',
    MiniGifPermissaoDono:            'https://media.tenor.com/Ggb25MyFi5kAAAAi/crown-royalty.gif',
    MiniGifPermissao:                'https://c.tenor.com/JSANcak2zVEAAAAC/little-giants-muscles.gif',
    MiniGifCadeado:                  'https://media4.giphy.com/media/5be91ClsRkXNDQn1fa/giphy.gif?cid=790b761189307d2cd843bd1ffb491b10a63c1839fe3912c3&rid=giphy.gif&ct=g',
    MiniGifHelp:                     'https://media.tenor.com/W1nmbKo97bYAAAAC/helprave-i-need-help.gif',
    Punido:                          'https://c.tenor.com/bbAQ2wzoecoAAAAC/spank-tom-and-jerry.gif',
    Perdão:                          'https://c.tenor.com/fIa6LTUEtmIAAAAC/imback.gif',
    WhatsApp:                        'https://cliply.co/wp-content/uploads/2021/08/372108180_WHATSAPP_ICON_400.gif',
    Discord:                         'https://i.pinimg.com/originals/0d/5a/7a/0d5a7a920f011a34adf1ccea5046fb2c.gif',
    Ideia:                           'https://c.tenor.com/dcZgOstfwbkAAAAi/gettingcreative-becreative.gif',
    Steam:                           'https://c.tenor.com/zjbXreUb5_YAAAAd/steam.gif',
    Defeito:                         'https://c.tenor.com/vBF_TDHCBvsAAAAC/broken-the-mitchells-vs-the-machines.gif',
    Doadores:                        'https://c.tenor.com/YjPBups7H48AAAAC/6m-rain.gif',
    Aviso:                           'https://media1.tenor.com/images/10a536f1abb9fd24986f4fb6cc967308/tenor.gif',
    Anuncio:                         'https://media.tenor.com/qfWPUeBXDxsAAAAd/bugs-bunny.gif',
    SalaErrada:                      'https://media1.tenor.com/images/54d526fd183bb842780b9df05ebf6af6/tenor.gif',
    Erro:                            'https://media2.giphy.com/media/TqiwHbFBaZ4ti/giphy.gif',
    PortaAberta:                     'https://i.imgur.com/G0K0NaU.gif',
    Lista:                           'https://i.gifer.com/Oqjp.gif',
    Numeros:                         'https://thumbs.gfycat.com/SleepyVainBedbug-size_restricted.gif',
    Anonimo:                         'https://c.tenor.com/OlkCUrnKZiwAAAAC/anonymous-glitching.gif',
    Help:                            'https://media.tenor.com/images/91097c2cbd4404743eac76a1a2798fca/tenor.gif',
    PermissaoNoob:                   'https://media.tenor.com/-Gb2OUA3I1MAAAAC/radioco-queen.gif',
    Permissao:                       'https://media.tenor.com/images/ccffe39a0a1f4e1ca5bae339bdb76470/tenor.gif',
    PortaFechada:                    'https://i.imgur.com/LiTsPX6.gif',
    Bug:                             'https://c.tenor.com/pPKOYQpTO8AAAAAM/monkey-developer.gif',
    Cla:                             'https://c.tenor.com/TiwA5rktxmAAAAAC/clash-of-clans-clash-gi-fs.gif',
    Saida:                           'https://i.imgur.com/R3A6OrI.gif',
    Saindo:                          'https://media1.tenor.com/images/cbc71e50841aa44a56050042a0412b0c/tenor.gif',
    AbrindoCadeado:                  'https://i.pinimg.com/originals/8c/cc/bc/8cccbcb7a42d2370ad4849bd5ba15937.gif',
    BanPv:                           'https://i.imgur.com/na1JgkH.gif',
    Ban:                             'https://i.imgur.com/BZIyPaS.gif',
    UnBanPv:                         'https://c.tenor.com/60EIA8ePILYAAAAC/im-back-woody.gif',
    UnBan:                           'https://c.tenor.com/fIa6LTUEtmIAAAAC/imback.gif',
    Help:                            'https://media.tenor.com/K5p4FSa0kUgAAAAi/help-northury.gif',
    Vergonha:                        'https://cdn.streamelements.com/uploads/655f4711-1433-4c0f-9aa0-6a9ae8b260c1.gif',
    ExpulsoPvMini:                   'https://c.tenor.com/dAjBzKj9H3AAAAAC/danger-alert.gif',
    Expulso:                         'https://images.milledcdn.com/2018-11-23/bZoa6B8SPTk43zJe/8K8BVyponJ27.gif',
    BoasVinda:                       'https://media.tenor.com/images/6a12a33514fc6846dfd4f3353f77745f/tenor.gif',
    SateliteCarregando:              'https://media.tenor.com/sa8CQ5x5BQIAAAAj/henrilauriano-satellite.gif',
    SatelitePronto:                  'https://media.tenor.com/7sbSZk4TL6QAAAAC/sending-signals.gif',
    Clear:                           'http://2.bp.blogspot.com/-dcLYYffAv2w/U1E3Un7Ie1I/AAAAAAAAAAw/uYYS4DWtJBk/s1600/1.gif',
    Confirmado:                      'https://www.sexyrede.com/themes/sunshine/reaction/like.gif',
    Skip:                            'https://inesquecivelcasamento.com.br/wp-content/uploads/2018/02/dj-gif.gif',
    Volume:                          'https://media1.tenor.com/images/620bf583496bd30c16d8a94562bfc5ff/tenor.gif',
    Bot:                             'https://media.tenor.com/fRw-3JZwfTwAAAAC/cryptoflash-crypto.gif',
    Comando:                         'https://miro.medium.com/v2/resize:fit:1358/1*Awi84KRY_5cFk9P0cIhtrw.gif',
    Comandos:                        'https://miro.medium.com/v2/resize:fit:1358/1*Awi84KRY_5cFk9P0cIhtrw.gif',
    ComandoBloqueado:                'https://media.tenor.com/WhZUcjq1mmsAAAAC/dislike-boo.gif',
    Block:                           'https://media.tenor.com/btrvHNki0pkAAAAd/salty-block.gif',
    VaiPutaria:                      'https://64.media.tumblr.com/tumblr_lxjjq0l6W51r3bw11o1_400.gif',
    SemImagem:                       'https://wingandaprayerdotlive.files.wordpress.com/2018/07/no-image-available.jpg',
    Discord:                         'https://media.tenor.com/uPh5mmsfEfEAAAAC/discord.gif',
    Cargos:                          'https://media.tenor.com/9dE4D2ajH6QAAAAC/discord-roles.gif',
    
    
    
    
    Barra:                           'https://i.imgur.com/M4yDcAq.png',
}

module.exports = gifs;

